CloudKids.Web/Controllers/ReclamationController.cs
using CloudKids.Data;
using CloudKids.Data.Infrastructure;
using CloudKids.Domain.Entities;
using CloudKids.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CloudKids.Web.Controllers
{
    public class ReclamationController : Controller
    {





        CloudKidsContext db = new CloudKidsContext();
        IDBFactory dbf;
        IUnitOfWork uow;
        IService<Reclamation> serviceRep;

        public ReclamationController()
        {
            dbf = new DBFactory();
            uow = new UnitOfWork(dbf);
            serviceRep = new Service<Reclamation>(uow);
        }




        // GET: Reclamation
        public ActionResult Index(string search)
        {
            if (search == null)
                return View(serviceRep.GetAll());
            else
                return View(serviceRep.GetAll().Where(x => x.Motif.Contains(search) || search == null));
        }

        // GET: Reclamation/Details/5
        public ActionResult Details(int id)
        {
            return View(serviceRep.GetById(id));
        }

        // GET: Reclamation/Create
        public ActionResult Create()
        {
          
           
            return View();
        }

        // POST: Reclamation/Create
        [HttpPost]
        public ActionResult Create(Reclamation R)
        {
            try
            {
                serviceRep.Add(R);
                serviceRep.Commit();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Reclamation/Edit/5
        public ActionResult Edit(int id)
        {
            var rep = serviceRep.GetById(id);
            return View(rep);
        }

        // POST: Reclamation/Edit/5
        [HttpPost]
        public ActionResult Edit(Reclamation reclamation)
        {
            try
            {

                var Rec = db.Reclamations.Single(c => c.Id == reclamation.Id);

                Rec.Motif = reclamation.Motif;  
                    Rec.ProfilJardinId = reclamation.ProfilJardinId;
                db.SaveChanges();
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Reclamation/Delete/5
        public ActionResult Delete(int id)
        {
            return View(serviceRep.GetById(id));
        }

        // POST: Reclamation/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {

                serviceRep.Delete(serviceRep.GetById(id));
                serviceRep.Commit();

                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CloudKids.Web/Views/Reclamation/Create.cshtml
@model CloudKids.Domain.Entities.Reclamation


@{
    ViewBag.Title = "Create";
}
<br /><br /><br /><br /><br /><br /><br /><br />
<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reclamation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Motif, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Motif, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Motif, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ProfilJardinId, "Profil Jardin", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProfilJardinId, new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.DropDownList("ProfilJardinId", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.ProfilJardinId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProfilParentId, "Profil Parent", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProfilParentId, new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.DropDownList("ProfilJardinId", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.ProfilParentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CloudKids.Web/Views/Reclamation/Delete.cshtml
@model CloudKids.Domain.Entities.Reclamation

@{
    ViewBag.Title = "Delete";
}
<br /><br /><br /><br /><br /><br /><br /><br />

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reclamation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProfilJardin.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfilJardin.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProfilParent.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfilParent.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Motif)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Motif)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CloudKids.Web/Views/Reclamation/Details.cshtml
@model CloudKids.Domain.Entities.Reclamation

@{
    ViewBag.Title = "Details";
}

<br /><br /><br /><br /><br /><br /><br /><br />
<h2>Details</h2>

<div>
    <h4>Reclamation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProfilJardin.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfilJardin.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProfilParent.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfilParent.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Motif)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Motif)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CloudKids.Web/Views/Reclamation/Edit.cshtml
@model CloudKids.Domain.Entities.Reclamation

@{
    ViewBag.Title = "Edit";
}
<br /><br /><br /><br /><br /><br /><br /><br />

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reclamation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Motif, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Motif, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Motif, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProfilJardinId, "Profil Jardin", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProfilJardinId, new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.DropDownList("ProfilJardinId", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.ProfilJardinId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProfilParentId, "Profil Parent", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProfilParentId, new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.DropDownList("ProfilJardinId", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.ProfilParentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CloudKids.Web/Views/Reclamation/Index.cshtml
@model IEnumerable<CloudKids.Domain.Entities.Reclamation>

@{
    ViewBag.Title = "Index";
}
<br /><br /><br /><br /><br /><br /><br /><br />
<h2>Index</h2>

<div class="widget widget-search">
    @using (Html.BeginForm("Index", "Reclamation", FormMethod.Get))
    {
        @Html.TextBox("search")
        <button type="submit"><i class="fa fa-search"></i></button>
    }
</div><!-- widget-search end-->
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProfilJardin.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProfilParent.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Motif)
        </th>
        <th></th>
    </tr>

@if (Model != null)
{
    foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProfilJardin.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProfilParent.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Motif)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
    }
}

</table>