CloudKids.Web/Controllers/ReputationController.cs
using CloudKids.Data;
using CloudKids.Data.Infrastructure;
using CloudKids.Domain.Entities;
using CloudKids.Service;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CloudKids.Web.Controllers
{
    public class ReputationController : Controller
    {



        CloudKidsContext db = new CloudKidsContext();
        IDBFactory dbf;
        IUnitOfWork uow;
        IService<Reputation> serviceRep;

        public ReputationController()
        {
            dbf = new DBFactory();
            uow = new UnitOfWork(dbf);
            serviceRep = new Service<Reputation>(uow);
        }
        // GET: Reputation
        public ActionResult Index(string search)
        {
            if (search == null)
                return View(serviceRep.GetAll());
            else
                return View(serviceRep.GetAll().Where(x => x.Type.ToString().Contains(search) || search == null));
        }

        // GET: Reputation/Details/5
        public ActionResult Details(int id)
        {
            return View(serviceRep.GetById(id));
        }

        // GET: Reputation/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Reputation/Create
        [HttpPost]
        public ActionResult Create(Reputation p)
        {
            try
            {

                serviceRep.Add(p);
                serviceRep.Commit();
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Reputation/Edit/5
        public ActionResult Edit(int id)
        {
            var rep = serviceRep.GetById(id);
            return View(rep);
        }

        // POST: Reputation/Edit/5
        [HttpPost]
        public ActionResult Edit(Reputation R)  
        {
            if (ModelState.IsValid)

            {
               var Rep =  db.Reputations.Single(c => c.Id == R.Id);
                Rep.Description = R.Description;
                Rep.Prix = R.Prix;
                Rep.Type = R.Type;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
              
                // TODO: Add update logic here

                return RedirectToAction("Index");
            
              return View();
            
        }

        // GET: Reputation/Delete/5
        public ActionResult Delete(int id)
        {
            return View(serviceRep.GetById(id));
        }

        // POST: Reputation/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                serviceRep.Delete(serviceRep.GetById(id));
                serviceRep.Commit();
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CloudKids.Web/Views/Reputation/Create.cshtml
@model CloudKids.Domain.Entities.Reputation

@{
    ViewBag.Title = "Create";
}

<br /><br /><br /><br /><br /><br /><br /><br />
<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Reputation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Type, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prix, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProfilJardinId, "ProfilJardinId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProfilJardinId, new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.DropDownList("ProfilJardinId", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.ProfilJardinId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CloudKids.Web/Views/Reputation/Delete.cshtml
@model CloudKids.Domain.Entities.Reputation

@{
    ViewBag.Title = "Delete";
}
<br /><br /><br /><br /><br /><br /><br /><br />
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reputation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProfilJardin.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfilJardin.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prix)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prix)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CloudKids.Web/Views/Reputation/Details.cshtml
@model CloudKids.Domain.Entities.Reputation

@{
    ViewBag.Title = "Details";
}
<br /><br /><br /><br /><br /><br /><br /><br />
<h2>Details</h2>

<div>
    <h4>Reputation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProfilJardin.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfilJardin.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prix)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prix)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CloudKids.Web/Views/Reputation/Edit.cshtml
@model CloudKids.Domain.Entities.Reputation

@{
    ViewBag.Title = "Edit";
}
<br /><br /><br /><br /><br /><br /><br /><br />
<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Reputation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Type, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prix, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CloudKids.Web/Views/Reputation/Index.cshtml
@model IEnumerable<CloudKids.Domain.Entities.Reputation>
    

@{
    ViewBag.Title = "Index";
}
<br /><br /><br /><br /><br /><br /><br /><br />
<h2>Index</h2>


<div class="widget widget-search">
    @using (Html.BeginForm("Index", "Reputation", FormMethod.Get))
    {
        @Html.TextBox("search")
        <button type="submit"><i class="fa fa-search"></i></button>
    }
</div><!-- widget-search end-->

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProfilJardin.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prix)
            </th>
            <th></th>
        </tr>
        @if (Model != null)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProfilJardin.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Prix)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }
        }

    </table>